/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package curencyConvertors;

/**
 *
 * @author User
 */
public class curencyConvertor extends javax.swing.JFrame {

        double USA = 178.62;
        double India = 2.60;
        double China = 26.59;
        double Canada = 133.65;
        double Indunisia = 0.013;
        
    public curencyConvertor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcmbCurrency = new javax.swing.JComboBox<String>();
        jlblConvert = new javax.swing.JLabel();
        jtxtConvert = new javax.swing.JTextField();
        jbnexit = new javax.swing.JButton();
        jbnreset = new javax.swing.JButton();
        jbnconvert = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(204, 204, 204));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 50)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 51, 51));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Curency Convertor");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));

        jcmbCurrency.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jcmbCurrency.setForeground(new java.awt.Color(0, 102, 204));
        jcmbCurrency.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Choose One ...", "USA", "India", "China", "Canada", "Indunisia" }));
        jcmbCurrency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcmbCurrencyActionPerformed(evt);
            }
        });

        jlblConvert.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jlblConvert.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlblConvert.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 5, true));

        jtxtConvert.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jtxtConvert.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jtxtConvert.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        jtxtConvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtConvertActionPerformed(evt);
            }
        });

        jbnexit.setBackground(new java.awt.Color(0, 0, 0));
        jbnexit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbnexit.setForeground(new java.awt.Color(255, 0, 0));
        jbnexit.setText("Exit");
        jbnexit.setToolTipText("");
        jbnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnexitActionPerformed(evt);
            }
        });

        jbnreset.setBackground(new java.awt.Color(51, 51, 51));
        jbnreset.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbnreset.setForeground(new java.awt.Color(255, 255, 51));
        jbnreset.setText("Reset");
        jbnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnresetActionPerformed(evt);
            }
        });

        jbnconvert.setBackground(new java.awt.Color(0, 102, 204));
        jbnconvert.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jbnconvert.setForeground(new java.awt.Color(255, 255, 255));
        jbnconvert.setText("Convert");
        jbnconvert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbnconvertActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jtxtConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcmbCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlblConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)))
                .addContainerGap(99, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jbnexit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbnreset)
                .addGap(87, 87, 87)
                .addComponent(jbnconvert)
                .addGap(60, 60, 60))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addComponent(jcmbCurrency, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jtxtConvert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jlblConvert, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbnexit)
                    .addComponent(jbnreset)
                    .addComponent(jbnconvert))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbnconvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnconvertActionPerformed
      try{
        double Srilankan_Rs = Double.parseDouble(jtxtConvert.getText());
        
        if(jcmbCurrency.getSelectedItem().equals("USA")){
        String cConvert1 = String.format("RS. %.2f", Srilankan_Rs * USA);
        jlblConvert.setText(cConvert1);
        }
        if(jcmbCurrency.getSelectedItem().equals("India")){
        String cConvert1 = String.format("RS. %.2f", Srilankan_Rs * India);
        jlblConvert.setText(cConvert1);
        }
        if(jcmbCurrency.getSelectedItem().equals("China")){
        String cConvert1 = String.format("RS. %.2f", Srilankan_Rs * China);
        jlblConvert.setText(cConvert1);
        }
        if(jcmbCurrency.getSelectedItem().equals("Canada")){
        String cConvert1 = String.format("RS. %.2f", Srilankan_Rs * Canada);
        jlblConvert.setText(cConvert1);
        }
        if(jcmbCurrency.getSelectedItem().equals("Indunisia")){
        String cConvert1 = String.format("RS. %.2f", Srilankan_Rs * Indunisia);
        jlblConvert.setText(cConvert1);
        }
      }catch(Exception exception){
          System.out.println("There'S A eeroe");
      }
    }//GEN-LAST:event_jbnconvertActionPerformed

    private void jbnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnexitActionPerformed
        System.exit(0);

    }//GEN-LAST:event_jbnexitActionPerformed

    private void jbnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbnresetActionPerformed
       jtxtConvert.setText(null);
       jlblConvert.setText(null);
       jcmbCurrency.setSelectedIndex(0);
    }//GEN-LAST:event_jbnresetActionPerformed

    private void jcmbCurrencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcmbCurrencyActionPerformed
        
    }//GEN-LAST:event_jcmbCurrencyActionPerformed

    private void jtxtConvertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtConvertActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtConvertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(curencyConvertor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(curencyConvertor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(curencyConvertor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(curencyConvertor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new curencyConvertor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton jbnconvert;
    private javax.swing.JButton jbnexit;
    private javax.swing.JButton jbnreset;
    private javax.swing.JComboBox<String> jcmbCurrency;
    private javax.swing.JLabel jlblConvert;
    private javax.swing.JTextField jtxtConvert;
    // End of variables declaration//GEN-END:variables
}
